# fly.toml app configuration file generated for huda-academy on 2025-03-04T17:07:54+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'huda-academy'
primary_region = 'sin'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
